version: "3.3"

networks:
  iot:
    driver: overlay
    attachable: true

services:

  flow:
    image: mojix/flow:latest
    hostname: flow
    volumes:
      - /data/flows:/flows
    networks:
      - iot
    deploy:
      resources:
        limits:
          memory: 3G
      placement:
        constraints:
          - node.labels.host == node0