version: "3.3"

networks:
  iot:
    driver: overlay
    attachable: true

services:
  ftpbridge1:
    image: mojix/riot-core-bridges:v6.72.18
    environment:
      VIZIX_BRIDGE_TYPE: agent
      AB_MQTTHOST: mqtt
      AB_MQTTPORT: 1883
      AB_LOGGER: stdout
      AB_SERVICES_HTTP_HOST: services
      AB_SERVICES_HTTP_PORT: 8080
      AB_SERVICES_API_KEY: ECTJDHW0TC
      AB_SERVICES_CONTEXT_PATH: /riot-core-services
      VIZIX_ESPER: 'no'
      AB_BROKER_TYPE : kafka
      AB_KAFKA_SERVERS: kafka:9092
      AB_AGENT_CODE: LAMETRO
    volumes:
      - /data/persistedFiles:/persistedFiles
    networks:
      - iot
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '0.5'
      placement:
        constraints:
          - node.labels.host == node0
