version: "3.3"

networks:
  iot:
    driver: overlay
    attachable: true

services:

  actionprocessor:
    image: mojix/riot-core-bridges:v6.72.18
    environment:
      VIZIX_BRIDGE_TYPE: actionprocessor
      VIZIX_KAFKA_SERVERS: kafka:9092
    networks:
      - iot
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.labels.host == node0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status"]
      interval: 50s
      timeout: 10s
      retries: 2
