version: "3.3"

networks:
  iot:
    driver: overlay
    attachable: true

services:

  reportgenerator:
    image: mojix/riot-core-bridges:v6.72.18
    environment:
      MEM_XMX: 1024m
      MEM_XMS: 1024m
      VIZIX_REPORT_GENERATOR_PRODUCT_THINGTYPE_FQN: /LAM/PRODUCT
      VIZIX_REPORT_GENERATOR_PRODUCT_DB_COLLECTION: productcube
      VIZIX_REPORT_GENERATOR_EPCISEVENT_THINGTYPE_FQN: /LAM/EPCISEVENT
      VIZIX_REPORT_GENERATOR_EPCISEVENT_DB_COLLECTION: epciseventcube
      VIZIX_REPORT_GENERATOR_CONTENT_THINGTYPE_FQN: /LAM/CONTENT
      VIZIX_REPORT_GENERATOR_REFERENCE_LIST_THINGTYPE_FQN: /LAM/REFERENCELIST
      VIZIX_REPORT_GENERATOR_REFERENCE_LIST_DB_COLLECTION: referencelistcube
      VIZIX_REPORT_GENERATOR_CATEGORY_THINGTYPE_FQN: /LAM/DEPARTMENTZONEMAPPING
      VIZIX_REPORT_GENERATOR_CATEGORY_DB_COLLECTION: categorycube
      VIZIX_REPORT_GENERATOR_STATUS_DB_COLLECTION: statuscube
      VIZIX_REPORT_GENERATOR_STATUS_THINGTYPE_FQN: /LAM/ITEM,/LAM/ITEMFINALSTATUS
      VIZIX_REPORT_GENERATOR_LOCATION_THINGTYPE_FQN: /LAM/LOCATION
      VIZIX_REPORT_GENERATOR_LOCATION_DB_COLLECTION: locationcube
      VIZIX_REPORT_GENERATOR_FIXTURE_THINGTYPE_FQN: /LAM/FIXTURE
      VIZIX_REPORT_GENERATOR_FIXTURE_DB_COLLECTION: fixturecube
      # Others.
      VIZIX_BRIDGE_TYPE: reportgenerator
      VIZIX_KAFKA_SERVERS: kafka:9092
      VIZIX_JAVA_METASPACE_SIZE: 200m
      VIZIX_PUBLISH_KAFKA_ENABLED: 'true'    #required to update bizlocations and itemlifecycle in realtime
      VIZIX_REPORT_GENERATOR_FUNCTIONS: ProductFunction,EPCISEventFunction,ContentFunction,ReferenceListFunction,LocationFunction,CategoryFunction,FixtureFunction,StatusFunction,ItemLifeCycleFunction #required to publish location, fixture and item life cycle events to update cache.
    networks:
      - iot
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.labels.host == node0
      resources:
        limits:
          memory: 2G

