version: "3.3"

networks:
  iot:
    driver: overlay
    attachable: true

services:

  transformbridge:
    image: mojix/riot-core-bridges:v6.72.18
    environment:
      VIZIX_BRIDGE_TYPE: 'transformbridge'
      VIZIX_KAFKA_SERVERS: 'kafka:9092'
      VIZIX_TRANSFORM_BRIDGE_SCRIPTS_DIRECTORY: '/var/vizix/transform'
      VIZIX_FIX_VIZIX_EVENT_ENABLE: 'true'
      VIZIX_KAFKA_PARAM_MAX_REQUEST_SIZE: 90000000
      VIZIX_KAFKA_PARAM_BUFFER_MEMORY: 90000000
    networks:
      - iot
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.labels.host == node0